# Temperature (°C)
TEMPERATURE_WARNING = 40.0
TEMPERATURE_CRITICAL = 50.0

# Gas concentration (ppm)
GAS_WARNING = 80
GAS_CRITICAL = 120

# Heart Rate (BPM)
HEART_RATE_WARNING = 100
HEART_RATE_CRITICAL = 130

# Humidity (%)
HUMIDITY_WARNING = 70
HUMIDITY_CRITICAL = 85

# Motion
MOTION_NORMAL = "Normal"
MOTION_FALL = "Fall"

# Risk Levels
RISK_NORMAL = "Normal"
RISK_WARNING = "Warning"
RISK_CRITICAL = "Critical"